run:
  timeout: 5m
  go: "1.23"

linters-settings:
  depguard:
    rules:
      main:
        allow:
          - $gostd
          - repository-context-protocol
          - github.com/vmihailenco/msgpack/v5
          - github.com/mattn/go-sqlite3
          - github.com/spf13/cobra
          - github.com/mark3labs/mcp-go/mcp
          - github.com/mark3labs/mcp-go/server
          - github.com/stretchr/testify
  govet:
    enable:
      - shadow
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 20
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 5
  misspell:
    locale: US
  lll:
    line-length: 140
  goimports:
    local-prefixes: repository-context-protocol
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint

linters:
  enable:
    - bodyclose
    - copyloopvar
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - mnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - mnd
        - funlen
        - goconst
        - gocyclo
    - path: internal/ast/golang/parser\.go
      text: "Function 'ParseFile' is too long"
      linters:
        - funlen
    - path: internal/mcp/tools\.go
      text: "Function 'collectDetailedStatistics' has too many statements"
      linters:
        - funlen
    - path: internal/index/hybrid\.go
      text: "Function 'extractFunctionFromSource' is too long"
      linters:
        - funlen
    - path: internal/mcp/context_tools\.go
      text: "Function 'buildFunctionImplementation' is too long"
      linters:
        - funlen
